### ISSUE TITLE
No More Save Game Or Import? Is That Just Me?

### ISSUE THREAD

**Issue by TheGSleazy** [jamesmgittins/dopeslingertycoon#36]
No More Save Game Or Import? Is That Just Me?

**Comment by jamesmgittins** [comment]
I removed it for the kongregate version to try to avoid cheaters. I've just put it back on the dopeslinger.gti.nz version now

**Comment by TheGSleazy** [comment]
that makes alot of sense thanks for explaining to me and thanks for putting it back on main website :) keep on working on it i love this game <3
